### ISSUE TITLE
[galimage] conversion of name tag picture crash with galimage

### ISSUE THREAD

**Issue by H0R1Z0N** [pmrowla/pylivemaker#30]
Commit of 31 march 2020
Python 3.8.2
RebornOS (Arch Linux Vanilla)
Anaheim's Girl's Love Story,

Trying to convert the contain of the folder グラフィック/名前 in anaheim to png. They are picture of the name tag of the character. The name tag's a static standalone picture, it's not animated nor packaged into a group.

command with example with one of the picture, repeat the same error for all picture in the folder.
$ galconvert 名前_軍人スコット.gal 名前_ 軍人スコット.png

Converting 名前_軍人スコット.gal to 名前_軍人スコット.png
Traceback (most recent call last):
  File "/home/hnt/.local/bin/galconvert", line 8, in <module>
    sys.exit(galconvert())
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/cli/cli.py", line 71, in galconvert
    im.load()
  File "/usr/lib/python3.8/site-packages/PIL/ImageFile.py", line 230, in load
    status, err_code = decoder.decode(b"")
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/GalImagePlugin.py", line 364, in decode
    mask = Image.frombuffer('L', size, alpha_data, 'raw', ('L', frame['alpha_stride']))
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2605, in frombuffer
    im = im._new(core.map_buffer(data, size, decoder_name, None, 0, args))
TypeError: argument 6 must be sequence of length 3, not 2

PS : I am mostly done with Anaheim outside of those picture and right menu click (Which i will be doing tomorrow).

**Comment by pmrowla** [comment]
This is related to #26. It's on my todo list but I've been busy with other work recently.

**Comment by H0R1Z0N** [comment]
I am in no hurry since i can always start a new project while waiting since i am still waiting for the few QC pass.

**Comment by pmrowla** [comment]
Can you try with the latest master? It should be fixed now for both `galconvert` and `lmar x --image-format=...`

**Comment by H0R1Z0N** [comment]
Both are still broken.

lmar x --image-format=png 名前_？？？.gal  

`Traceback (most recent call last):
  File "/home/hnt/.local/bin/lmar", line 8, in <module>
    sys.exit(lmar())
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/cli/lmar.py", line 59, in x
    with LMArchive(input_file) as lm:
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/archive.py", line 501, in __init__
    raise e
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/archive.py", line 467, in __init__
    self._parse_directory()
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/archive.py", line 592, in _parse_directory
    directory = LMArchiveDirectory.struct().parse_stream(self.fp)
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 320, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 2561, in _parse
    raise ConstError("parsing expected %r but parsed %r" % (self.value, obj), path=path)
construct.core.ConstError: Error in path (parsing) -> signature
parsing expected b'vf' but parsed b'Ga'
`

galconvert 名前_？？？.gal 名前_？？？.png  

`
Converting 名前_？？？.gal to 名前_？？？.png
Traceback (most recent call last):
  File "/home/hnt/.local/bin/galconvert", line 8, in <module>
    sys.exit(galconvert())
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/cli/cli.py", line 71, in galconvert
    im.load()
  File "/usr/lib/python3.8/site-packages/PIL/ImageFile.py", line 230, in load
    status, err_code = decoder.decode(b"")
  File "/home/hnt/.local/lib/python3.8/site-packages/livemaker/GalImagePlugin.py", line 364, in decode
    mask = Image.frombuffer('L', size, alpha_data, 'raw', ('L', frame['alpha_stride']))
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2605, in frombuffer
    im = im._new(core.map_buffer(data, size, decoder_name, None, 0, args))
TypeError: argument 6 must be sequence of length 3, not 2`

**Comment by pmrowla** [comment]
You may need to rerun `pip install -e .` or however you installed from git?

```Image.frombuffer('L', size, alpha_data...```
from your error message should be 
```
Image.frombytes('L', size, alpha_data...
```
in current master

https://github.com/pmrowla/pylivemaker/blob/master/livemaker/GalImagePlugin.py#L392

**Comment by H0R1Z0N** [comment]
It was indeed because of a cache issue, forced a reinstall of the python setup.py and it worked.
![image](https://user-images.githubusercontent.com/5923207/79673561-b9357a80-81a8-11ea-999d-a9362313f077.png)

**Comment by H0R1Z0N** [comment]
lmar x --image-format=png  名前_？？？.gal 
> Traceback (most recent call last):
>   File "/usr/bin/lmar", line 11, in <module>
>     load_entry_point('pylivemaker==0.2.3.dev0', 'console_scripts', 'lmar')()
>   File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/hnt/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/pylivemaker-0.2.3.dev0-py3.8.egg/livemaker/cli/lmar.py", line 65, in x
>     with LMArchive(input_file) as lm:
>   File "/usr/lib/python3.8/site-packages/pylivemaker-0.2.3.dev0-py3.8.egg/livemaker/archive.py", line 682, in __init__
>     raise e
>   File "/usr/lib/python3.8/site-packages/pylivemaker-0.2.3.dev0-py3.8.egg/livemaker/archive.py", line 647, in __init__
>     self._parse_directory()
>   File "/usr/lib/python3.8/site-packages/pylivemaker-0.2.3.dev0-py3.8.egg/livemaker/archive.py", line 781, in _parse_directory
>     directory = LMArchiveDirectory.struct().parse_stream(self.fp)
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 320, in parse_stream
>     return self._parsereport(stream, context, "(parsing)")
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 332, in _parsereport
>     obj = self._parse(stream, context, path)
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 2000, in _parse
>     subobj = sc._parsereport(stream, context, path)
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 332, in _parsereport
>     obj = self._parse(stream, context, path)
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 2489, in _parse
>     return self.subcon._parsereport(stream, context, path)
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 332, in _parsereport
>     obj = self._parse(stream, context, path)
>   File "/home/hnt/.local/lib/python3.8/site-packages/construct/core.py", line 2561, in _parse
>     raise ConstError("parsing expected %r but parsed %r" % (self.value, obj), path=path)
> construct.core.ConstError: Error in path (parsing) -> signature
> parsing expected b'vf' but parsed b'Ga'

lmar's not  working but galconvert work.

**Comment by pmrowla** [comment]
lmar is for extracting the full game archive/exe. The image format option lets you auto convert .gal images when extracting a game for the first time

**Comment by H0R1Z0N** [comment]
So i am guessing it's kinda fixed because it do work now.
