### ISSUE TITLE
Menu extraction does not work

### ISSUE THREAD

**Issue by Stefan311** [pmrowla/pylivemaker#60]
* pylivemaker version: 1.0.0-dev (20b2a05)
* Python version: 3.6.9
* Operating System: Linux
* LiveMaker game:

### Description

Menu extraction does not work in current API version.

This is usual text menu code:
```
 887: Calc 選択実行中 = 1
 888: VarNew _tmp ParamType.Str  2
 889: VarNew _tmpno ParamType.Int  2
 890: VarNew _tmpid ParamType.Str  2
 891: Calc AddArray(_tmp, "プロローグを見る")
 892: Calc _tmpno = 0
 893: Calc _tmpid = AddDelimiter("\r\n", _tmpid) ++ _tmpno
 894: Calc AddArray(_tmp, "プロローグを見ない")
 895: Calc _tmpno = 1
 896: Calc _tmpid = AddDelimiter("\r\n", _tmpid) ++ _tmpno
 897: Calc TrimArray(_tmp)
 898: If ArrayToString(_tmp) != ""
 899:     If 1
 900:         Call ノベルシステム\選択メニュー\■選択実行.lsb:0  1 ArrayToString(_tmp) 0 "C" "C" 0 "" "" 1
 901:         Calc 選択実行中 = 0
 902:         Calc StringToArray(_tmpid, _tmpid)
 903:         If 選択番号 >= 0
 904:             Calc 選択番号 = _tmpid[選択番号]
 905:     Else
 906:         Calc 選択値 = _tmp
 907:         Calc 選択番号 = _tmpno
 908:         Calc 選択実行中 = 0
 909:         Calc 右クリックメニュー一時禁止 = 0
 910:         Call ノベルシステム\メッセージボックス\終了.lsb:0  1 
 911:         Wait GetProp("メッセージボックス", 50) != "" 0 0
 912:     ObjDel "VOICE"
 913: VarDel _tmp
 914: VarDel _tmpno
 915: VarDel _tmpid
 916: Jump 00000003.lsb:1025 選択値 == "プロローグを見る"
 917: Jump 00000003.lsb:1015 1
 918: Wait 1 0 0
```
I have traced this issue.
The Menu detection starts on 887, which is correct.
The _find_choices finds both AddArray cmd's, but go until Line 901, because "選択実行中 = 0" found.
The _find_int_jumps starts at 902, skips 904 because of it's indention, and exits on 911 because Wait cmd. The menu jumps will be missed.

The _find_choices have to stop more early. So it skips the whole If ... else block because of it's indention.

I also think it's not a good idea of using the text representation of the commands for searching. If you ever change the text conversation of the command, you are in risk to break the menu functions.

**Comment by pmrowla** [comment]
Ok, so the issue is that menu syntax is not as standard per LM version as we thought it is. For reference, the game I was going off of always has the `Calc StringToArray` before the If/Else like here:
```
  29: Calc _tmpno = 1
  30: Calc _tmpid = AddDelimiter("\r\n", _tmpid) ++ _tmpno
  31: Calc _tmp = Trim(ArrayToString(_tmp))
  32: Calc StringToArray(_tmp, _tmp)
  33: If ArrayToString(_tmp) != ""
```
can you send me one of your LSB's with menus in it?

> I also think it's not a good idea of using the text representation of the commands for searching. If you ever change the text conversation of the command, you are in risk to break the menu functions.

With the way LM's TLiveParser expression syntax works, the regex matching will be safe as long as you aren't changing variable names.

**Comment by pmrowla** [comment]
Yeah going off of the calc function enum, TrimArray was added in one of the last LM versions, and Trim has existed since the initial one. But for versions where TrimArray is available, they can do the Trim + StringToArray in a single command instead of needing 2 commands to do it. So that will be something we need to account for

**Comment by pmrowla** [comment]
this is also something that would potentially benefit from #47, since the "fill array" commands would be in one `walk` iteration up until the first `If <array not empty>` conditional branch, but that's more of a "after 1.0" future improvement

**Comment by Stefan311** [comment]
> Can you send me one of your LSB's with menus in it?
Sure 
[0000015E.lsb.zip](https://github.com/pmrowla/pylivemaker/files/4622947/0000015E.lsb.zip)
This one have one special case beside from some normal menus.
```
2102: Calc _tmpid = AddDelimiter("\r\n", _tmpid) ++ _tmpno
2103: If (淫乱 == 1 & 自宅裏_夜男組_小便 > 0)
2104:     Calc AddArray(_tmp, "奥の枝を揺らす")
2105:     Calc _tmpno = 1
2106:     Calc _tmpid = AddDelimiter("\r\n", _tmpid) ++ _tmpno
2107: Calc AddArray(_tmp, "思い切ってボールに手を伸ばす")
```
A conditional menu entry!

> edit: although I'm thinking now that you probably meant using the command order?
No, you got me right at the first. I just found it wrong to first package informations into a string in human readable format. After that we extracting this information from string back to a machine format. That's two unnecessary conversions.

**Comment by pmrowla** [comment]
thanks for the LSB

> No, you got me right at the first. I just found it wrong to first package informations into a string in human readable format. After that we extracting this information from string back to a machine format. That's two unnecessary conversions.

Ah I see. The thing is that Calc expressions are meant to be human readable strings. They are just actually just LM's [expression syntax](https://pylivemaker.readthedocs.io/en/latest/_static/LiveNovel/calc.html) packed into a binary format. The LiveParser is just that syntax parsed into an operator (like `==`) and two or more operands (so left-hand side and right-hand side, result, etc). (and functions like AddArray count as operators).

So for something like `選択値 = _tmp`, the packed LiveParser basically just contains the sequence

* (right hand side) operand Var (variable name) `_tmp`
* (left hand side) operand Var `選択値`
* operator `=` (assignment) left-hand side = right-hand side

where the operands are given names like `____N` where N is just an index (but for some functions may be a named tmp var), and `____0` is always the "result" operand.

(note that in LM's syntax, any string that is not `"` quoted is a treated as a var name, and string literals **must** be `"` quoted)

What pylm *should* have is proper expression support that will just let us write `Calc(`選択値 = _tmp`)` and understand how to pack entire expression properly as operator/operand sequences. We should be operating on packing and replacing entire expressions, rather than editing individual, already-packed operand fields. But unfortunately we do not have that yet, so for example if we wanted to change the right hand side to a new var name, or even to a string literal, we have to manually find the packed operand corresponding to `_tmp` and edit it that way.

The reason that `lmlsb edit` does so much ugly stuff to edit individual operand fields by hand is that there is no proper string expression parser yet.

But pylm does at least unpack expressions into the correct/original human-readable form, so we can at least take advantage of that when trying to find the commands we are looking for.

**Comment by pmrowla** [comment]
basically with regard to calc expressions, right now pylm is able to do the equivalent of extracting a TpWord block into an LNS script, but is unable to take a modified LNS script and recompile it back into a TpWord block.

**Comment by Stefan311** [comment]
Ok, let's continue.
I have done this:
`        if str(calc) in cls.END_SELECTION_CALCS + ["StringToArray(_tmp, _tmp)"] + ["TrimArray(_tmp)"]:`

now this new error:
`KeyError: 'No matching jump for menu choice プロローグを見ない'`

Of coarse there is no jump for this. It is handled by the `Jump 00000003.lsb:1015 1`

**Comment by pmrowla** [comment]
@Stefan311 should be fixed now, if it isn't just reopen the issue

**Comment by pmrowla** [comment]
oops, forgot to include the insert changes

**Comment by Stefan311** [comment]
extract worked, I am auto-translating now. 
Let's see who is faster: Google translate or your insert change :)

**Comment by pmrowla** [comment]
ok, insert should work now

**Comment by Stefan311** [comment]
Still not work properly:
`... invalid text block: LSB command '887' is not start of a menu ...`
I add some debugging log:
```
    def from_lsb_command(cls, lsb, start, pylm=None):
        try:
            cmd = lsb.commands[start]
            print(f"from_lsb_command start={start} cmd_line={cmd.LineNo}")
            if not cls.is_menu_start(cmd):
                raise NotSelectionMenuError
```
Result (extract):
```
Extracting 00000003.lsb ...
from_lsb_command start=1123 cmd_line=855
2 Menu entries extracted.
```
Result (insert)
```
Patching 00000003.lsb ...
from_lsb_command start=887 cmd_line=659
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pylivemaker-1.0.0.dev0-py3.6.egg/livemaker/lsb/lmscript.py", line 669, in replace_menu_choices
    menu = make_menu(self, line_no)
  File "/usr/local/lib/python3.6/dist-packages/pylivemaker-1.0.0.dev0-py3.6.egg/livemaker/lsb/menu.py", line 452, in make_menu
    raise NotSelectionMenuError
livemaker.lsb.menu.NotSelectionMenuError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lmlsb", line 11, in <module>
    load_entry_point('pylivemaker==1.0.0.dev0', 'console_scripts', 'lmlsb')()
  File "/home/stefan/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/stefan/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stefan/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stefan/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pylivemaker-1.0.0.dev0-py3.6.egg/livemaker/cli/lmlsb.py", line 1065, in insertmenu
    translated, failed, untranslated = _patch_csv_menus(lsb, lsb_file, csv_data, verbose)
  File "/usr/local/lib/python3.6/dist-packages/pylivemaker-1.0.0.dev0-py3.6.egg/livemaker/cli/lmlsb.py", line 1112, in _patch_csv_menus
    translated, failed = lsb.replace_text(text_objects)
  File "/usr/local/lib/python3.6/dist-packages/pylivemaker-1.0.0.dev0-py3.6.egg/livemaker/lsb/lmscript.py", line 558, in replace_text
    t, f = self.replace_menu_choices(new_objs["menu-text"])
  File "/usr/local/lib/python3.6/dist-packages/pylivemaker-1.0.0.dev0-py3.6.egg/livemaker/lsb/lmscript.py", line 671, in replace_menu_choices
    raise BadTextIdentifierError(f"invalid text block: LSB command '{line_no}' is not start of a menu")
livemaker.exceptions.BadTextIdentifierError: invalid text block: LSB command '887' is not start of a menu
```
The commands array-index is different from cmd.LineNo !

**Comment by Stefan311** [comment]
Strange!

```
    for i in range(len(lsb.commands)):
        print(f"Index={i} LineNo={lsb.commands[i].LineNo}")
```
Result:
```
...
Index=29 LineNo=29
Index=30 LineNo=30
Index=31 LineNo=31
Index=32 LineNo=31
Index=33 LineNo=32
Index=34 LineNo=33
...
```
Double line number 31!

**Comment by pmrowla** [comment]
Yes, index is not always the same as LineNo. That’s a live maker engine thing, not a pylm thing. Basically, for loop related commands, a single “While” is compiled into multiple binary commands, but they are all assigned the same LineNo. And for other things, when commands are deleted (because the user edited their game workflow) LiveMaker does not always re-index all of the commands in the LSB. So you can end up with LineNo values that don’t match the actual binary index.

**Comment by pmrowla** [comment]
But yeah, just attach the problematic LSB and I’ll take a look

**Comment by pmrowla** [comment]
@Stefan311 the issue w/mixing index and LineNo for menu insert should be fixed in master now
